### PR TITLE
Expose a programmatic API for consumers

### PR DESCRIPTION
**Pull request by phated**
This is my attempt at making a programmatic API for consumers of the circom2 npm package (such as hardhat-circom and zkrepl). I'm not 100% happy with a class-based API, but it helped to encapsulate the WASI stuff.

I haven't tested it out in either project, but it seems that using `unionfs` and then pushing node's `fs` on top of the stack allows all of the current tests to complete.

I also looked through available nodejs APIs and found that we can basically just use your `performance.now()` shim for hrtime and I tried to make the random byte filling cross-platform.

### CODE REVIEW

**Comment by phated** [comment]
Thinking out loud about the API a bit. We could change it to a function that returns a "WebAssembly-like" object:
```js
function create({ args, env, preopens = defaultPreopens, bindings = defaultBindings } = {}) {
   const wasi = new WASI({
        args: ['circom2', ...args],
        env,
        preopens,
        bindings,
    });

    return {
         compile() { ... }
         instantiate() { ... }
         start() { ... }
    }
}
```

**Comment by phated** [comment]
@antimatter15 I decided to remove the `memfs` stuff because I need to do weird `unionfs` stuff in hardhat-circom. The CLI here should only need node's `fs` and zkrepl will only need `memfs`. The only reason I tried implementing it here was because I needed https://github.com/streamich/unionfs/pull/713 but I just PR'd that upstream and published a scoped fork until they accept.

**Comment by antimatter15** [comment]
@phated is this at a state where you'd be comfortable with me merging this?

**Comment by phated** [comment]
Yep, I'm pretty happy with the current implementation!

**Pull request merged**
